[MA : Completed Functionality of TODO App]
mihirarora28082000/TodoApp pull request #2
Opened 2023-04-03 12:29 UTC by mihirarora28082000

2023-04-03 12:55 UTC, Ayush-gupta-josh requested changes

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/task_card.dart
> +  Color color(int priority) {
Improve function naming convention

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/task_card.dart
> +    if (priority == 1) {
what does 1 represent? Using descriptive names for contact value

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/task_card.dart
> +                    color: Colors.green,
Note: Ideally Frontend uses a theme structure these colors should be passed through theme. C

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/task_card.dart
> +                  ? snackBar(context, 'Task Marked as Completed !', true)
Static text should be stored in constant

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/task_card.dart
> +                                        4 - widget.task.priority.toDouble(),
Try to make code readable

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/snackbar.dart
> +import 'package:flutter/material.dart';
Move this Util

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/widgets/modal_bottom.dart
> +      }));
Add limiting rule trailing comas

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/presentation/screen/todo_screen.dart
> +                }
break down this complete function into smaller functions

2023-04-03 12:55 UTC, Ayush-gupta-josh commented on lib/bloc/todo_bloc.dart
> +  }
Why these are part of bloc files

2023-04-03 13:10 UTC, mihirarora28082000 commented on lib/bloc/todo_bloc.dart
> +  }
I am actually using HydratedBloc State here. These are the functions which it expects us to override.

2023-04-04 05:42 UTC, mihirarora28082000 commented on lib/presentation/widgets/snackbar.dart
> +import 'package:flutter/material.dart';
Done

2023-04-04 11:08 UTC, mihirarora28082000 commented on lib/presentation/widgets/task_card.dart
> +    if (priority == 1) {
done

2023-04-04 11:08 UTC, mihirarora28082000 commented on lib/presentation/widgets/task_card.dart
> +  Color color(int priority) {
done

2023-04-04 11:08 UTC, mihirarora28082000 commented on lib/presentation/widgets/task_card.dart
> +                  ? snackBar(context, 'Task Marked as Completed !', true)
done

2023-04-04 11:09 UTC, mihirarora28082000 commented on lib/presentation/widgets/task_card.dart
> +                                        4 - widget.task.priority.toDouble(),
done

2023-04-04 11:09 UTC, mihirarora28082000 commented on lib/presentation/screen/todo_screen.dart
> +                }
done

2023-04-04 11:36 UTC, mihirarora28082000 commented on lib/presentation/widgets/modal_bottom.dart
> +      }));
fixed

2023-04-06 13:59 UTC, merged